-- DDL
-- ALTER : 객체를 수정하는 구문
-- 테이블 객체 수정 : ALTER TABLE 테이블명 수정할 내용;
-- 컬럼 추가/변경/삭제, 제약조건 추가/변경/삭제
-- 테이블명 변경, 제약조건 이름 변경

-- 컬럼 추가
SELECT
        DC.*
   FROM DEPT_COPY DC;
   
ALTER TABLE DEPT_COPY
ADD (LNAME VARCHAR2(20));

SELECT
        DC.*
   FROM DEPT_COPY DC;
   
-- 컬럼 삭제
ALTER TABLE DEPT_COPY
DROP COLUMN LNAME;

SELECT
        DC.*
   FROM DEPT_COPY DC;

-- 컬럼 생성 시 DEFAULT값 설정
ALTER TABLE DEPT_COPY
ADD(CNAME VARCHAR(20) DEFAULT '한국');

SELECT
        DC.*
   FROM DEPT_COPY DC;
   
-- 컬럼에 제약조건 추가
CREATE TABLE DEPT_COPY2
AS
SELECT D.*
  FROM DEPARTMENT D;
  
SELECT
        DC.*
   FROM DEPT_COPY2 DC;

ALTER TABLE DEPT_COPY2
ADD CONSTRAINT PK_DEPT_ID2 PRIMARY KEY(DEPT_ID);

ALTER TABLE DEPT_COPY2
ADD CONSTRAINT UN_DEPT_ID2 UNIQUE(DEPT_TITLE);

ALTER TABLE DEPT_COPY2
MODIFY LOCATION_ID CONSTRAINT NN_LID NOT NULL;

-- 컬럼 자료형 수정
ALTER TABLE DEPT_COPY2
MODIFY DEPT_ID CHAR(3)
MODIFY DEPT_TITLE VARCHAR(30)
MODIFY LOCATION_ID VARCHAR(2);

-- 컬럼의 크기를 줄이는 경우에는
-- 변경하려는 크기를 초과하는 값이 없을 때만 변경할 수 있다.
ALTER TABLE DEPT_COPY2
MODIFY DEPT_TITLE VARCHAR2(10);

SELECT
        DC.*
   FROM DEPT_COPY DC;
   
-- DEFAULT 값 변경
ALTER TABLE DEPT_COPY
MODIFY CNAME DEFAULT '미국';

SELECT
        DC.*
   FROM DEPT_COPY DC;
   
INSERT
   INTO DEPT_COPY
VALUES
(
  'D0'
, '생산부'
, 'L2'
, DEFAULT
);

SELECT
        DC.*
   FROM DEPT_COPY DC;
   
SELECT
        DC.*
   FROM DEPT_COPY2 DC;
   
ALTER TABLE DEPT_COPY2
DROP COLUMN DEPT_TITLE;

ALTER TABLE DEPT_COPY2
DROP COLUMN LOCATION_ID;

-- 지우려는 테이블에 최소 한 개 이상의 컬럼이 남아 있어야함
ALTER TABLE DEPT_COPY2
DROP COLUMN DEPT_ID;

CREATE TABLE TB1(
  PK NUMBER PRIMARY KEY,
  FK NUMBER REFERENCES TB1,
  COL1 NUMBER,
  CHECK(PK > 0 AND COL1 > 0 )
);

ALTER TABLE TB1
DROP COLUMN PK;

ALTER TABLE TB1
DROP COLUMN PK CASCADE CONSTRAINT;

SELECT
        T.*
   FROM TB1 T;
   
-- 컬럼 삭제
-- 테이블에 최소 한 개 이상의 컬럼이 존재해야 함 : 모든 컬럼 삭제는 불가능하다.
-- 데이터가 괴록되어 있는 컬럼도 삭제 가능함
-- 삭제된 컬럼은 복구가 안됨
SELECT
        DC.*
   FROM DEPT_COPY DC;
   
ALTER TABLE DEPT_COPY
DROP (CNAME, DEPT_TITLE, LOCATION_ID);

SELECT
        DC.*
   FROM DEPT_COPY DC;
   
ROLLBACK;

-- 제약조건 삭제
CREATE TABLE CONST_EMP(
   ENAME VARCHAR2(20) NOT NULL,
   ENO VARCHAR2(15) NOT NULL,
   MARRIAGE CHAR(1) DEFAULT 'N',
   EID CHAR(3),
   EMAIL VARCHAR2(30),
   JID CHAR(2),
   MID CHAR(3),
   DID CHAR(2),
   CONSTRAINT CK_MARRIAGE CHECK(MARRIAGE IN ('Y', 'N')),
   CONSTRAINT PK_EID PRIMARY KEY(EID),
   CONSTRAINT UN_ENO UNIQUE(ENO),
   CONSTRAINT UN_EMALI UNIQUE(EMAIL),
   CONSTRAINT FK_JID FOREIGN KEY(JID)
   REFERENCES JOB(JOB_CODE) ON DELETE SET NULL,
   CONSTRAINT FK_MID FOREIGN KEY(MID)
   REFERENCES CONST_EMP ON DELETE SET NULL,
   CONSTRAINT FK_DID FOREIGN KEY(DID)
   REFERENCES DEPARTMENT ON DELETE CASCADE
);

ALTER TABLE CONST_EMP
DROP CONSTRAINT CK_MARRIAGE;

ALTER TABLE CONST_EMP
DROP CONSTRAINT FK_DID
DROP CONSTRAINT FK_JID
DROP CONSTRAINT FK_MID;

ALTER TABLE CONST_EMP
MODIFY (ENAME NULL, ENO NULL);

-- 컬럼 이름 변경
CREATE TABLE DEPT_COPY3
AS
SELECT * FROM DEPARTMENT;

SELECT
        DC.*
   FROM DEPT_COPY3 DC;
   
ALTER TABLE DEPT_COPY3
RENAME COLUMN DEPT_ID TO DEPT_CODE;

SELECT
        DC.*
   FROM DEPT_COPY3 DC;
   
ALTER TABLE DEPT_COPY3
ADD CONSTRAINT PK_DEPT_CODE3 PRIMARY KEY(DEPT_CODE);

ALTER TABLE DEPT_CODE3
RENAME CONSTRAINT PK_DEPT_CODE3 TO PK_DCODE;

ALTER TABLE DEPT_COPY3
RENAME TO DEPT_TEST;

SELECT
        DC.*
   FROM DEPT_COPY3 DC;
   
SELECT
        DT.*
   FROM DEPT_TEST DT;
   
-- 테이블 삭제
DROP TABLE DEPT_TEST CASCADE CONSTRAINT;