-- 시퀀스(SEQUENCE)
-- 자동 번호 발생기 역할을 하는 객체
/*
CREAE SEQUENCE 시퀀스
(INCREMAENT BY 숫자) -- 다음 값에 대한 증가치, 생략하면 자동 1 기본
(START WITH 숫자) -- 처음 발생시킬 값 지정, 생략하면 자동 1 기본
(MAXVALUE 숫자 | NOMAXVALUE) -- 발생시킬 최대값 지정
(MINVALUE 숫자 | NOMINVALUE) -- 최소값 지정
(CYCLE | NOCYCLE) -- 값 순환 여부
(CACHE 크기 | NOCHCHE) -- 캐시 사용 여부, 기본값은  20
*/

CREATE SEQUENCE SEQ_EMPID
START WITH 300
INCREMENT BY 5
MAXVALUE 310
NOCYCLE
NOCACHE;

SELECT SEQ_EMPID.NEXTVAL FROM DUAL;

SELECT * FROM USER_SEQUENCES;

ALTER SEQUENCE SEQ_EMPID
INCREMENT BY 10
MAXVALUE 400
NOCYCLE
NOCACHE;

SELECT * FROM USER_SEQUENCES;

-- START WITH값은 변경 불가
-- START WITH 값을 변경하고자 하려면 오브젝트를 삭제하고 다시 생성해야 한다.

DROP SEQUENCE SEQ_EMPID;

-- SELECT 문에서 사용 가능
-- INSERT 문에서 SELECT 구문에서 사용가능
-- INSERT 문에서 VALUE 절에서 사용 가능
-- UPDATE 문에서 SET 절에서 사용 가능

-- 단, 서브쿼리의 SELECT문에서는 사용 불가
-- VIWE의 SELECT절에서 사용 불가
-- DISTINCT 키워드가 있는 SELECT에서 사용 불가
-- GROUP BY, HAVING 절이 있는 SELECT문에서 사용 불가
-- ORDER BY 절에서 사용 불가
-- CREATE TABLE, ALTER TABLE의 DEFAULT 값으로 사용 불가

CREATE SEQUENCE SEQ_EID
START WITH 300
INCREMENT BY 1
MAXVALUE 10000
NOCYCLE
NOCACHE;

INSERT INTO EMPLOYEE A
(
  A.EMP_ID, A.EMP_NAME, A.EMP_NO, A.EMAIL, A.PHONE
, A.DEPT_CODE, A.JOB_CODE, A.SAL_LEVEL, A.SALARY, A.BONUS
, A.MANAGER_ID, A.HIRE_DATE, A.ENT_DATE, A.ENT_YN
)
VALUES
(
  SEQ_EID.NEXTVAL, '홍길동', '666666-6666666', 'hong123@greedy.com', '01012345678'
, 'D2', 'J7', 'S1', 5000000, 0.1
, '200', SYSDATE, NULL, DEFAULT
);

SELECT * FROM EMPLOYEE;

ROLLBACK;

CREATE SEQUENCE SEQ_EID2;

